version: "3"

services:
  database:
    container_name: omero-database
    image: "postgres:14"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    # This container uses the tag for the latest server release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    container_name: omero-server
    image: "openmicroscopy/omero-server:5"
    env_file: 
      - ./.env
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      CONFIG_omero_jvmcfg_percent_blitz: 50
      CONFIG_Ice_MessageSizeMax: 1000000
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"
    ulimits:
      nofile:
        soft: 8192
        hard: 65536

  omeroweb:
    # This container uses the tag for the latest web release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    container_name: omero-web-standalone
    # image: "openmicroscopy/omero-web-standalone:5"
    # build: https://github.com/vernonlim/omero-web-docker.git#master:standalone
    build:
      context: ../omero-web-docker/standalone
      dockerfile: ./Dockerfile
    environment:
      OMEROHOST: omeroserver
      CONFIG_omero_web_public_enabled: true
      CONFIG_omero_web_public_user: nottingham
      CONFIG_omero_web_public_password: nottingham
      CONFIG_omero_web_public_get__only: true
      CONFIG_omero_web_public_server__id: 1
      CONFIG_omero_web_public_url__filter: '^/(webadmin/myphoto/|webclient/(?!(script_ui|ome_tiff|figure_script))|webgateway/(?!(archived_files|download_as))|iviewer|api|omero_crm_landing_page|gallery|public_datasets)'
      CONFIG_omero_web_csrf__trusted__origins: '["https://omero.vernonlim.dev", "https://vernonlim.dev", "http://localhost:5173"]'
      CONFIG_omero_web_cors__allowed__origins: '["http://localhost:5173"]'
      CONFIG_omero_web_cors__allowed__methods: '["GET", "POST", "PUT", "DELETE", "OPTIONS"]'
      CONFIG_omero_web_cors__allowed__headers: '["Content-Type", "Authorization"]'
      CONFIG_omero_web_cors__allow__credentials: 'true'
      CONFIG_omero_web_gallery_category__queries: > 
        {
          "all": {
            "label": "All", 
            "index": 0, 
            "query": "FIRST50:Name"
          },
          "tracking": {
            "label":"3D tracking",
            "index":0, 
            "query":"Study Type: 3D-tracking"
           },
           "publication_authors": {
           "label": "Publication Authors", 
           "index": 1, 
           "query": "Publication Authors: Publication Authors"
          },
           "Imaging Method": {
           "label": "Imaging Method", 
           "index": 1, 
           "query": "Imaging Method: Imaging Method"
          },
           "Patient ID": {
           "label": "Patient ID", 
           "index": 1, 
           "query": "Patient ID: Patient ID"
          }
        }
      CONFIG_omero_web_gallery_filter__keys: >
        [
          "Name",
          {"label": "Imaging Method", "value": "Imaging Method"},
          {"label": "Publication Authors", "value": "Publication Authors"},
          {"label": "Study Type", "value": "Study Type"},
          {"label": "Patient ID", "value": "Patient ID"}
        ]
    networks:
      omero:
        aliases:
          - omeroweb
    ports:
      - "4080:4080"
    # expose:
    #   - "4080"
    volumes:
      - "/Users/jkling/Desktop/SEGP/omero_crm_landing_page/omero_crm_landing_page:/opt/omero/web/venv3/lib/python3.9/site-packages/omero_crm_landing_page:ro"
      - "/Users/jkling/Desktop/SEGP/omero_crm_landing_page/omero_crm_landing_page:/opt/omero/web/venv3/lib64/python3.9/site-packages/omero_crm_landing_page:ro"
      - "./config.omero:/opt/omero/web/config/config.omero:ro"
      - "/Users/jkling/Desktop/SEGP/resources/logo.png:/opt/omero/web/OMERO.web/lib/python/omero_web/static/omero_web/img/logo.png:ro"
      - "/Users/jkling/Desktop/SEGP/omero-imjoy:/opt/omero-imjoy"
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../nginx/reverse_proxy.conf:/etc/nginx/nginx.conf
      - ../nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/vernonlim.dev.pem:/etc/nginx/cert/vernonlim.dev.pem
      - ../nginx/vernonlim.dev.key:/etc/nginx/cert/vernonlim.dev.key
    networks:
      - omero
    ports:
      - 80:80
      - 443:443

networks:
  omero:

volumes:
  database:
  omero:
